### ISSUE TITLE
Broken pipe when uploading pizero files

### ISSUE THREAD

**Issue by sebbacon** [tech4nature/hogapp#35]
Presumably this is related to timeouts - perhaps the pizero videos are particularly large.

I don't have a precise bug report, but @Gabrielkyne says:

> Not copying over the files from pizero - see email with error, a broken pipe on server side guessing  - probably a problem if there is a backlog of  - ok with extended time and no backlog of videos-must schedule upload rate say 1 every 5 mins?  - OUTSTANDING 

And this is the traceback:

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 936, in _send_output
    self.send(message_body)
  File "/usr/lib/python3.5/http/client.py", line 908, in send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 936, in _send_output
    self.send(message_body)
  File "/usr/lib/python3.5/http/client.py", line 908, in send
    self.sock.sendall(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hedge.py", line 190, in <module>
    PIZERO_IP_MAX, PIZERO_FTP_USERNAME, PIZERO_FTP_PASSWORD)
  File "hedge.py", line 163, in main
    post(box_id, rfid_tag, to_post)  # Posts data
  File "hedge.py", line 103, in post
    box_id, "hog-" + hog_id, "/home/pi/Videos/" + file, time
  File "/home/pi/HogPi/app/client.py", line 53, in upload_video
    return requests.put(url, files=files, auth=AUTH).json()
  File "/home/pi/.local/lib/python3.5/site-packages/requests/api.py", line 131, in put
    return request('put', url, data=data, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
```

**Comment by sebbacon** [comment]
It seems likely that these are simply much larger files. @jw2476 could you report on the file sizes of the ext videos compared with the RPi ones? Thanks

**Comment by neiljw1** [comment]
The external files will be same size as internal ones, possiblity slightly smaller as no audio

**Comment by sebbacon** [comment]
OK. Is it worth double checking? 

As I understand the problem, files are being correctly transferred *to* the RPi, from where they are posted *by* the RPi; so the posting process is identical for all files, regardless of origin. 

Yet the external files and *only* the external files are resulting in a `ConnectionError`.

If all the above is correct, then the only plausible explanation is that the files themselves are somehow different.

Alternatively, some of the above could be incorrect, i.e. the diagnosis that it's always external videos is wrong, and in fact it's random videos.  Is there a way of confirming this?

**Comment by neiljw1** [comment]
Not without access to the Pi's, it looks like we can't access them
remotely. I might go and get the box and bring it here, but it's Jack's
birthday tomorrow, so might not happen until Friday

Neil
