### ISSUE TITLE
Heroku geodjango build broken

### ISSUE THREAD

**Issue by sebbacon** [tech4nature/hogapp#54]
Unable to do any deploys. 

```
remote: -----> $ python hog/manage.py collectstatic --noinput
remote:        Traceback (most recent call last):
remote:          File "/tmp/build_5cd42f97/hog/manage.py", line 17, in <module>
remote:            execute_from_command_line(sys.argv)
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
remote:            utility.execute()
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
remote:            django.setup()
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
remote:            apps.populate(settings.INSTALLED_APPS)
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
remote:            app_config = AppConfig.create(entry)
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/django/apps/config.py", line 224, in create
remote:            import_module(entry)
remote:          File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
remote:            return _bootstrap._gcd_import(name[level:], package, level)
remote:          File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
remote:          File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
remote:          File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
remote:          File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
remote:          File "<frozen importlib._bootstrap_external>", line 855, in exec_module
remote:          File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/mapwidgets/__init__.py", line 4, in <module>
remote:            from .widgets import GooglePointFieldWidget, GooglePointFieldInlineWidget, \
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/mapwidgets/widgets.py", line 4, in <module>
remote:            from django.contrib.gis.forms import BaseGeometryWidget
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/django/contrib/gis/forms/__init__.py", line 3, in <module>
remote:            from .fields import (  # NOQA
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/django/contrib/gis/forms/fields.py", line 2, in <module>
remote:            from django.contrib.gis.gdal import GDALException
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
remote:            from django.contrib.gis.gdal.datasource import DataSource
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/django/contrib/gis/gdal/datasource.py", line 40, in <module>
remote:            from django.contrib.gis.gdal.driver import Driver
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
remote:            from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
remote:            from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/django/contrib/gis/gdal/libgdal.py", line 53, in <module>
remote:            lgdal = CDLL(lib_path)
remote:          File "/app/.heroku/python/lib/python3.9/ctypes/__init__.py", line 374, in __init__
remote:            self._handle = _dlopen(self._name, mode)
remote:        OSError: libblas.so.3: cannot open shared object file: No such file or directory
remote: 
remote:  !     Error while running '$ python hog/manage.py collectstatic --noinput'.

```

**Comment by sebbacon** [comment]
On my laptop, the library is provided by `libblas3`:

    libblas3:amd64: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3

Which is apparently installed during the heroku build:

    remote: -----> Installing libblas3_3.7.1-4ubuntu1_amd64.deb

However, libblas is actually *not* installed:

    ~ $ dpkg -la | grep libblas
    ~ $

**Comment by sebbacon** [comment]
OK, so [heroku-buildfile-apt](https://github.com/heroku/heroku-buildpack-apt) installs in `.apt/usr/lib/x86_64-linux-gnu/blas/libblas.so.3` and adds `export LD_LIBRARY_PATH="$HOME/.apt/usr/lib/x86_64-linux-gnu:$HOME/.apt/usr/lib/i386-linux-gnu:$HOME/.apt/usr/lib:$LD_LIBRARY_PATH"` in `$HOME/.profile.d/000_apt.sh`.

**Comment by sebbacon** [comment]
Frustratingly, this works:

```sh
$ python
Python 3.9.5 (default, May  3 2021, 18:33:38) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
>>> lgdal.heko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/.heroku/python/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/app/.heroku/python/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /app/.heroku/vendor/lib/libgdal.so.20: undefined symbol: heko

```

Note that this is actually the libblas provided by `heroku-geo-buildpack`

**Comment by sebbacon** [comment]
Even worse so does this:
```
~ $ python hog/manage.py collectstatic --noinput

0 static files copied to '/app/hog/staticfiles', 205 unmodified, 424 post-processed.
```

**Comment by sebbacon** [comment]
OK so to recap `python hog/manage.py collectstatic --noinput` works fine when you run `heroku run bash` from the  command line but not when it's done as part of the build process. I can only assume this is an ordering thing, i.e.
